"""Flux-consumption relations.

PF flux contribution and resistive, internal and external flux consumed over the
ramp-up, plus the central-solenoid flat-top duration. All scalar and SI-consistent
(Wb, H, A, T, m, V, s).
"""

from typing import Any

import numpy as np

from fusdb import relation
from fusdb.registry import MU0


@relation(
    name="Internal flux",
    tags=("plasma", "current_drive", "tokamak"),
    outputs="internal_flux",
)
def calc_internal_flux(I_p: Any, internal_inductance: Any) -> Any:
    """Flux due to the plasma current and internal inductance.

    Adapted from cfspopcon; see README.md section "Third-party Notices".
    :cite:`Barr_2018`.
    """
    # CHECK
    return I_p * internal_inductance


@relation(
    name="External flux",
    tags=("plasma", "current_drive", "tokamak"),
    outputs="external_flux",
)
def calc_external_flux(I_p: Any, external_inductance: Any) -> Any:
    """Surface flux generated by the plasma current.

    Adapted from cfspopcon; see README.md section "Third-party Notices".
    :cite:`Barr_2018`.
    """
    # CHECK
    return I_p * external_inductance


@relation(
    name="Resistive flux",
    tags=("plasma", "current_drive", "tokamak"),
    outputs="resistive_flux",
)
def calc_resistive_flux(I_p: Any, R: Any, ejima_coefficient: Any = 0.4) -> Any:
    """Resistive flux consumed over the ramp-up (Ejima).

    Adapted from cfspopcon; see README.md section "Third-party Notices".
    :cite:`Gribov_2007`, :cite:`Menard_2001`.
    """
    # CHECK
    return ejima_coefficient * MU0 * I_p * R


@relation(
    name="Poloidal field flux",
    tags=("plasma", "current_drive", "tokamak"),
    outputs="poloidal_field_flux",
)
def calc_poloidal_field_flux(vertical_field_mutual_inductance: Any, vertical_magnetic_field: Any, R: Any) -> Any:
    """Surface flux contribution from the vertical (PF-coil) field.

    Adapted from cfspopcon; see README.md section "Third-party Notices".
    :cite:`Barr_2018`.
    """
    # CHECK
    return np.pi * R**2 * vertical_field_mutual_inductance * vertical_magnetic_field


@relation(
    name="Flux needed from solenoid over rampup",
    tags=("plasma", "current_drive", "tokamak"),
    outputs="flux_needed_from_CS_over_rampup",
)
def calc_flux_needed_from_solenoid_over_rampup(
    internal_flux: Any, external_flux: Any, resistive_flux: Any, poloidal_field_flux: Any
) -> Any:
    """Total flux needed from the central solenoid over the ramp-up.

    Adapted from cfspopcon; see README.md section "Third-party Notices".
    """
    # CHECK
    return internal_flux + external_flux + resistive_flux - poloidal_field_flux


@relation(
    name="Maximum flattop duration",
    tags=("plasma", "current_drive", "tokamak"),
    outputs="max_flattop_duration",
)
def calc_max_flattop_duration(
    total_flux_available_from_CS: Any, flux_needed_from_CS_over_rampup: Any, loop_voltage: Any
) -> Any:
    """Maximum flat-top duration drivable by the central solenoid.

    Adapted from cfspopcon; see README.md section "Third-party Notices".
    """
    # CHECK
    max_flux_for_flattop = total_flux_available_from_CS - flux_needed_from_CS_over_rampup
    return max_flux_for_flattop / loop_voltage


@relation(
    name="Breakdown flux consumption",
    tags=("plasma", "current_drive", "tokamak"),
    outputs="breakdown_flux_consumption",
)
def calc_breakdown_flux_consumption(R: Any) -> Any:
    """Resistive flux required for breakdown.

    Adapted from cfspopcon; see README.md section "Third-party Notices".
    :cite:`Sugihara`.
    """
    # CHECK
    return 0.073 * R - 0.00665
