"""Confinement and scaling relation helpers."""

from .scalings import (
    CONFINEMENT_RELATIONS,
    CONFINEMENT_RELATIONS_BY_NAME,
    STELLARATOR_CONFINEMENT_RELATIONS,
    TOKAMAK_CONFINEMENT_RELATIONS,
)

__all__ = [
    "CONFINEMENT_RELATIONS",
    "CONFINEMENT_RELATIONS_BY_NAME",
    "TOKAMAK_CONFINEMENT_RELATIONS",
    "STELLARATOR_CONFINEMENT_RELATIONS",
]
