"""fusdb vs PROCESS across a tungsten concentration sweep.

Reference: ``reference/tungsten_sweep/`` -- five evaluation-mode PROCESS runs at
W = 5e-6 .. 1e-4, generated by ``reference/scripts/fusdb_tungsten_sweep.ex.py``.

This is the quantitative form of PROCESS's own
``single_model_evaluation.ex.py``, which raises tungsten from 5e-6 to 5e-5 and
observes radiated power rise and separatrix power fall.  That example prints its
two states at runtime and commits no reference numbers, so only the *direction*
of the response is recorded upstream.

A sweep tests something a single point cannot: whether fusdb responds to a
composition change the way PROCESS does.  A trend is also far more robust than
an absolute comparison, because a systematic offset shared by every point
cancels out of the response.
"""

from __future__ import annotations

import pytest

from _process_compare import COMPARED, FIELDS, TOLERANCE, compare
from _process_fixture import tungsten_sweep

# Both codes place these below the L-H threshold -- see test_lh_sustainment_agrees.
UNSUSTAINED = {"w_1.0e-04"}

# RESOLVED 2026-08-07 -- empty, and the exclusion it existed for is gone.
# `w_5.0e-05` used to report `regime_bistable`: the h-mode solve landed at
# P_sep/P_LH = 0.968, just under its own guard, so the walk moved on and settled
# on l_mode -- a branch that is inconsistent by construction, with P_sep +669%,
# P_aux +890% and tau_E -71% against PROCESS.
# It was never a dithering band.  fusdb was computing A_p with the SAUTER shape
# model while this MFILE was produced with i_plasma_shape = 0, PROCESS's
# two-intersecting-arcs model.  That made A_p +8.06%, hence P_LH +7.57%
# (P_LH ~ A_p^0.941), which pushed a genuinely H-mode point below threshold.
# Selecting the arc geometry the run actually used (see _process_fixture.py)
# makes A_p and P_LH exact, and the point sits at P_sep/P_LH = 1.041 --
# H-mode outright, regime_path ['h_mode'], on PROCESS's curve at P_sep -0.9%.
BISTABLE: set[str] = set()

# Points whose powers are not on PROCESS's h-mode curve, for either reason.
OFF_CURVE = UNSUSTAINED | BISTABLE

# (point, field) pairs that exceed 10%, carried as xfail so a future improvement
# surfaces as an xpass rather than passing silently.
#
# All of them are P_sep, or Q_sci inheriting it.  P_sep = P_in - P_rad is a
# difference of two large numbers, so the few-percent residuals in the heating
# and radiated powers amplify as radiation grows: at W = 5e-5 the radiated power
# has risen to ~297 MW against a ~420 MW heating power, and a 2% error in each
# becomes >10% in the ~120 MW remainder.
# Narrowed 2026-08-01: helium now radiates (the He bridge no longer prunes on a
# D-T machine), so P_rad rises ~2% and the P_sep remainder tightens.  The
# w_2.0e-05 P_sep and w_5.0e-05 Q_sci gaps closed outright.
# EMPTIED 2026-08-07: the last entry was ("w_5.0e-05", "P_sep") at +15.6%, kept
# dormant behind the BISTABLE exclusion.  Selecting PROCESS's own arc geometry
# put that point back on the h-mode curve at -0.9%, so the gap is closed rather
# than merely dormant.  The amplification argument above still holds; repopulate
# if it recurs.
KNOWN_GAPS: dict[tuple[str, str], str] = {}


@pytest.fixture(scope="module")
def sweep():
    """Solve every tungsten point once for the whole module."""
    return {tag: compare(path) for tag, path in tungsten_sweep().items()}


def test_all_points_solve(sweep):
    """Every point reconciles; the sustained ones stay in H-mode."""
    for tag, (_, result) in sweep.items():
        if tag in UNSUSTAINED:
            continue
        assert result["success"], f"{tag}: {result['failed_relations']}"
        # A bistable point still reconciles; it is only its regime verdict that
        # is a convention disagreement, so it keeps the success assertion.
        if tag in BISTABLE:
            continue
        assert result["regime"] == "h_mode", f"{tag} fell to {result['regime']}"


def test_lh_sustainment_agrees(sweep):
    """fusdb and PROCESS agree on which points can sustain H-mode.

    This is a real agreement, not a convention.  At W = 1e-4 PROCESS's own
    output reports P_sep = 0.00 MW against P_LH = 106.4 MW, so H-mode is not
    sustainable there -- PROCESS simply keeps using the confinement scaling its
    input file declares, whereas fusdb *derives* the regime and drops to ohmic.
    Both codes are saying the same thing about the physics.
    """
    for tag, (fields, result) in sweep.items():
        if tag in BISTABLE:
            continue
        process_sustains = fields["P_sep"]["process"] >= fields["P_LH"]["process"]
        # `regime` is the mode REPORTED (the declared assumption when nothing is
        # admissible); `regime_admissible` is the mode set actually CERTIFIED --
        # both the mode's relations AND its certifiers agreeing on that mode's
        # own solve.  A sustainment claim must read the latter.
        fusdb_sustains = "h_mode" in (result.get("regime_admissible") or [])
        assert process_sustains == fusdb_sustains, (
            f"{tag}: PROCESS sustains={process_sustains}, fusdb sustains={fusdb_sustains}"
        )


def test_radiation_rises_and_separatrix_power_falls(sweep):
    """The response the upstream example demonstrates, in both codes.

    Restricted to the H-mode-sustained points: once a point drops out of H-mode
    the confinement scaling changes underneath it, so its powers are not on the
    same curve and a monotonicity check across the discontinuity is meaningless.
    """
    tags = [t for t in sorted(sweep, key=lambda t: float(t.split("_")[1])) if t not in OFF_CURVE]
    ordered = [sweep[tag][0] for tag in tags]
    for key, direction in (("P_rad", +1), ("P_sep", -1)):
        for side in ("fusdb", "process"):
            series = [entry[key][side] for entry in ordered]
            deltas = [b - a for a, b in zip(series, series[1:])]
            assert all(direction * d > 0 for d in deltas), (
                f"{side} {key} is not monotonic in tungsten: {series}"
            )


def test_radiation_response_magnitude(sweep):
    """How much P_rad rises per decade of tungsten agrees within 10%.

    The response itself -- not just its sign -- which is what makes this a test
    of the radiation model rather than of its calibration.
    """
    tags = sorted(sweep, key=lambda t: float(t.split("_")[1]))
    low, high = sweep[tags[0]][0], sweep[tags[-1]][0]
    response = {
        side: high["P_rad"][side] - low["P_rad"][side] for side in ("fusdb", "process")
    }
    rel = (response["fusdb"] - response["process"]) / response["process"]
    assert abs(rel) <= TOLERANCE, (
        f"P_rad response to tungsten: fusdb {response['fusdb']/1e6:.1f} MW vs "
        f"PROCESS {response['process']/1e6:.1f} MW = {rel:+.2%}"
    )


@pytest.mark.parametrize("name", sorted(COMPARED))
def test_within_tolerance(sweep, name, request):
    """Each quantity is within 10% of PROCESS at every H-mode-sustained point."""
    for tag in sorted(sweep):
        if tag in OFF_CURVE:
            continue
        entry = sweep[tag][0][name]
        if abs(entry["rel_error"]) > TOLERANCE and (tag, name) in KNOWN_GAPS:
            request.node.add_marker(pytest.mark.xfail(reason=KNOWN_GAPS[(tag, name)], strict=False))
        assert abs(entry["rel_error"]) <= TOLERANCE, (
            f"{tag} {name}: fusdb {entry['fusdb']:.6g} vs "
            f"PROCESS {entry['process']:.6g} = {entry['rel_error']:+.2%}"
        )
