"""fusdb vs PROCESS across one-at-a-time plasma input perturbations.

Reference: ``reference/plasma_variants/`` -- nine evaluation-mode PROCESS runs
generated by ``reference/scripts/fusdb_plasma_variants.ex.py``: a baseline plus
``alphat``, ``alphan``, ``kappa`` and the xenon fraction each moved above and
below it.

The point is the **differential**.  Single-point agreement is weak evidence when
a fixture supplies most of the design vector -- it can look right for the wrong
reasons.  Asking whether fusdb *moves the same way* PROCESS does when one input
changes is much harder to pass by accident, and a systematic offset shared by
both the baseline and the variant cancels out of the difference entirely.

Each knob was chosen to move plasma physics without going through a model fusdb
does not have.  ``scan.ex.py`` sweeps the peak TF field and
``optimum_solutions_comparison.ex.py`` varies the required net electric power;
both move the design point through TF-coil and plant power-balance models that
fusdb has no counterpart for, so neither is reproducible here.
"""

from __future__ import annotations

import pytest

from _process_compare import COMPARED, FIELDS, TOLERANCE, compare
from _process_fixture import plasma_variants

BASELINE = "baseline"

# Both codes place this below the L-H threshold: PROCESS's own output gives
# P_sep = 39.7 MW against P_LH = 104.0 MW.  See test_lh_sustainment_agrees.
UNSUSTAINED = {"fndimpurityelectrons13_9.000e-04"}

# Exceedances carried as xfail so an improvement surfaces as an xpass.  Both are
# the same mechanism as in the tungsten sweep: P_sep = P_in - P_rad is a
# difference of large numbers, and at kappa = 1.75 the plasma is smaller while
# the radiated power rises to ~292 MW, so the residuals amplify in the remainder.
# Emptied 2026-08-01: both kappa_1.750e+00 gaps closed once helium started
# radiating (the He bridge no longer prunes on a D-T machine).
KNOWN_GAPS: dict[tuple[str, str], str] = {
    # +10.3%: fusdb's thermal pressure now counts the TOTAL ion density
    # n_i = n_fuel + n_imp (all ions), so W_th and hence P_aux carry the impurity
    # ion pressure PROCESS omits here.  The impurity ion number is tiny
    # (n_imp/n_fuel ~ 0.07%), but P_aux is a difference of large numbers and this
    # kappa=1.75 point is the high-radiation one, so the 0.07% amplifies past the
    # 10% band.  Physically correct; carried as a known fusdb<->PROCESS gap.
    ("kappa_1.750e+00", "P_aux"): "+10.3%: total-ion thermal pressure vs PROCESS fuel-only",
}

# Quantities whose response to a perturbation is compared.  Restricted to the
# extensive ones a plasma input actually moves; P_sep/Q_sci are excluded because
# their difference-of-large-numbers amplification dominates the delta.
RESPONSE_FIELDS = ("P_fus", "P_rad", "W_th", "tau_E", "V_p")


@pytest.fixture(scope="module")
def variants():
    """Solve every variant once for the whole module."""
    return {tag: compare(path) for tag, path in plasma_variants().items()}


def test_all_points_solve(variants):
    """Every variant reconciles; the sustained ones stay in H-mode."""
    for tag, (_, result) in variants.items():
        if tag in UNSUSTAINED:
            continue
        assert result["success"], f"{tag}: {result['failed_relations']}"
        assert result["regime"] == "h_mode", f"{tag} fell to {result['regime']}"


def test_lh_sustainment_agrees(variants):
    """fusdb and PROCESS agree on which variants can sustain H-mode."""
    for tag, (fields, result) in variants.items():
        process_sustains = fields["P_sep"]["process"] >= fields["P_LH"]["process"]
        # `regime` is the mode REPORTED (the declared assumption when nothing is
        # admissible); `regime_admissible` is the mode set actually CERTIFIED --
        # both the mode's relations AND its certifiers agreeing on that mode's
        # own solve.  A sustainment claim must read the latter.
        fusdb_sustains = "h_mode" in (result.get("regime_admissible") or [])
        assert process_sustains == fusdb_sustains, (
            f"{tag}: PROCESS sustains={process_sustains}, fusdb sustains={fusdb_sustains} "
            f"(reported regime {result['regime']}, admissible {result.get('regime_admissible')})"
        )


@pytest.mark.parametrize("name", RESPONSE_FIELDS)
def test_response_to_perturbation(variants, name):
    """fusdb's change from baseline matches PROCESS's, within 10%.

    Compared relative to the baseline value rather than to the delta itself: a
    delta that is near zero in both codes would otherwise blow up the relative
    error while representing perfect agreement.
    """
    base = variants[BASELINE][0]
    for tag in sorted(variants):
        if tag == BASELINE or tag in UNSUSTAINED:
            continue
        entry, base_entry = variants[tag][0][name], base[name]
        d_fusdb = (entry["fusdb"] - base_entry["fusdb"]) / base_entry["fusdb"]
        d_process = (entry["process"] - base_entry["process"]) / base_entry["process"]
        assert abs(d_fusdb - d_process) <= TOLERANCE, (
            f"{tag} {name}: fusdb responds {d_fusdb:+.2%}, "
            f"PROCESS responds {d_process:+.2%}"
        )


def test_responses_are_not_all_trivial(variants):
    """Guard: the perturbations actually moved something.

    Without this the response test above would pass vacuously if the fixture
    silently ignored the perturbed input -- which is exactly the failure mode
    that hid a discarded H-factor in the reactor library for so long.
    """
    base = variants[BASELINE][0]
    moved = 0
    for tag in variants:
        if tag == BASELINE:
            continue
        for name in RESPONSE_FIELDS:
            relative = abs(variants[tag][0][name]["process"] / base[name]["process"] - 1.0)
            moved += relative > 0.01
    assert moved >= 5, f"only {moved} responses exceeded 1%; perturbations look inert"


@pytest.mark.parametrize("name", sorted(COMPARED))
def test_within_tolerance(variants, name, request):
    """Each quantity is within 10% of PROCESS at every sustained variant."""
    for tag in sorted(variants):
        if tag in UNSUSTAINED:
            continue
        entry = variants[tag][0][name]
        if abs(entry["rel_error"]) > TOLERANCE and (tag, name) in KNOWN_GAPS:
            request.node.add_marker(pytest.mark.xfail(reason=KNOWN_GAPS[(tag, name)], strict=False))
        assert abs(entry["rel_error"]) <= TOLERANCE, (
            f"{tag} {name}: fusdb {entry['fusdb']:.6g} vs "
            f"PROCESS {entry['process']:.6g} = {entry['rel_error']:+.2%}"
        )
