from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path
import pkgutil

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

project = "fusdb"
author = "fusdb contributors"

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinxcontrib.bibtex",
]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

myst_enable_extensions = [
    "colon_fence",
]

bibtex_bibfiles = [str((Path(__file__).parent / "references.bib").resolve())]
bibtex_default_style = "unsrt"
bibtex_reference_style = "label"

exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "LicenseNotes.md",
    "_generated/*",
]

html_theme = "sphinx_rtd_theme"
html_extra_path = ["relations_variables_graph.html"]

def _order_with_preference(items: list[str], preferred: list[str]) -> list[str]:
    remaining = set(items)
    ordered: list[str] = []
    for name in preferred:
        if name in remaining:
            ordered.append(name)
            remaining.remove(name)
    ordered.extend(sorted(remaining))
    return ordered


def _generate_core_api(app) -> None:
    """Generate a reST file listing non-relation modules."""
    import fusdb

    modules: list[str] = []
    packages: list[str] = []
    for module in pkgutil.walk_packages(fusdb.__path__, prefix=f"{fusdb.__name__}."):
        name = module.name
        if name.endswith(".__init__"):
            continue
        if name.split(".")[-1].startswith("_"):
            continue
        if name.startswith("fusdb.relations"):
            continue
        if module.ispkg:
            packages.append(name)
            continue
        modules.append(name)

    core_modules: list[str] = []
    registry_modules: list[str] = []
    other_groups: dict[str, list[str]] = defaultdict(list)

    for module in modules:
        rel = module[len("fusdb.") :]
        if rel.startswith("registry."):
            registry_modules.append(module)
        elif "." not in rel:
            core_modules.append(module)
        else:
            group = rel.split(".")[0].replace("_", " ").title()
            other_groups[group].append(module)

    if "fusdb.registry" in packages:
        registry_modules.insert(0, "fusdb.registry")

    preferred_core = [
        "fusdb",
        "fusdb.reactor_class",
        "fusdb.relation_class",
        "fusdb.relationsystem_class",
        "fusdb.variable_class",
        "fusdb.relation_util",
        "fusdb.utils",
    ]
    core_modules = _order_with_preference(core_modules, preferred_core)
    if "fusdb" not in core_modules:
        core_modules.insert(0, "fusdb")

    def add_heading(text: str, underline: str) -> list[str]:
        return [text, underline * len(text), ""]

    def module_block(name: str) -> list[str]:
        return [
            f".. automodule:: {name}",
            "   :members:",
            "   :member-order: bysource",
            "   :show-inheritance:",
            "",
        ]

    lines: list[str] = [
        "Core",
        "====",
        "",
        ".. This file is auto-generated by docs/conf.py.",
        "",
    ]

    for module_name in core_modules:
        lines.extend(module_block(module_name))

    if registry_modules:
        lines.extend(add_heading("Registry", "-"))
        for module_name in _order_with_preference(registry_modules, ["fusdb.registry"]):
            lines.extend(module_block(module_name))

    for group in sorted(other_groups.keys()):
        lines.extend(add_heading(group, "-"))
        for module_name in sorted(other_groups[group]):
            lines.extend(module_block(module_name))

    out_dir = Path(__file__).parent / "_generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "core_api.rst").write_text("\n".join(lines))


def _generate_relations_api(app) -> None:
    """Generate a reST file listing all relation modules."""
    import fusdb.relations as relations

    modules: list[str] = []
    for module in pkgutil.walk_packages(relations.__path__, prefix=f"{relations.__name__}."):
        if module.ispkg:
            continue
        name = module.name
        if name.endswith(".__init__"):
            continue
        if name.split(".")[-1].startswith("_"):
            continue
        modules.append(name)

    tree: dict[str, dict[str | None, list[str]]] = defaultdict(lambda: defaultdict(list))
    prefix = f"{relations.__name__}."
    for module in modules:
        rel = module[len(prefix) :]
        parts = rel.split(".")
        if len(parts) == 1:
            top = "Misc"
            sub = None
        elif parts[0] == "power_balance" and len(parts) > 1:
            top = "Power Balance"
            sub = parts[1].replace("_", " ").title()
        else:
            top = parts[0].replace("_", " ").title()
            sub = None
        tree[top][sub].append(module)

    out_dir = Path(__file__).parent / "_generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "relations_api.rst"
    legacy_path = out_dir / "relations_api.md"
    if legacy_path.exists():
        legacy_path.unlink()

    def add_heading(text: str, underline: str) -> list[str]:
        return [text, underline * len(text), ""]

    def module_block(name: str) -> list[str]:
        return [
            f".. automodule:: {name}",
            "   :members:",
            "   :member-order: bysource",
            "   :show-inheritance:",
            "",
        ]

    lines: list[str] = [
        "Relations",
        "=========",
        "",
        ".. This file is auto-generated by docs/conf.py.",
        "",
    ]

    for top in sorted(tree.keys()):
        lines.extend(add_heading(top, "-"))
        submap = tree[top]
        if len(submap) == 1 and None in submap:
            for module_name in sorted(submap[None]):
                lines.extend(module_block(module_name))
            continue

        if None in submap:
            lines.extend(add_heading("General", "~"))
            for module_name in sorted(submap[None]):
                lines.extend(module_block(module_name))

        for sub in sorted(key for key in submap.keys() if key is not None):
            lines.extend(add_heading(sub, "~"))
            for module_name in sorted(submap[sub]):
                lines.extend(module_block(module_name))

    out_path.write_text("\n".join(lines))


def setup(app) -> None:
    app.connect("builder-inited", _generate_core_api)
    app.connect("builder-inited", _generate_relations_api)
