"""Shared result-assembly and option-validation helpers for execution modes.

These build the mode-flavored result dict and validate mode options. They were
moved off ``RelationSystem`` because they produce execution-layer output, not
compiled-system primitives. Functions that need compiled-system state take the
system as their first argument (mirroring :func:`fusdb.modes.verify.verify_values`);
the pure formatting/validation helpers take none.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any


def new_result(system: Any, mode: str) -> dict[str, Any]:
    return {
        "mode": mode,
        "success": False,
        "termination": "not run",
        "errors": [],
        "warnings": [],
        "compiler_report": system.compiler_report,
    }


def result_from_certificate(
    system: Any,
    mode: str,
    certificate: Mapping[str, Any],
    *,
    termination: str,
    solver: Mapping[str, Any] | None = None,
    include_values: bool = False,
    extra: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Build a mode result dict from a verification certificate.

    Shared by verify/reconcile/optimize so the one lean result shape is
    assembled in one place: ``mode``/``success``/``termination``/``errors``/
    ``warnings``, the per-relation ``relation_status``, the hoisted
    certificate verdicts (``failed_relations``, ``max_residual``) and the
    ``compiler_report``.  Everything in it is plain data (strings, numbers,
    numpy arrays), so results pickle across process pools and save to HDF5
    without a stripping pass.  ``solver`` and ``values`` are added only when
    supplied, and ``extra`` overlays any mode-specific keys.
    """
    result = new_result(system, mode)
    result.update(
        {
            "relation_status": certificate["relation_status"],
            "errors": certificate["errors"],
            "warnings": certificate["warnings"],
            "termination": termination,
            "success": bool(certificate["verified"]),
            "failed_relations": list(certificate["failed_relations"]),
            "max_residual": float(certificate["max_residual"]),
        }
    )
    if include_values:
        result["values"] = certificate["values"]
    if solver is not None:
        result["solver"] = dict(solver)
    if extra:
        result.update(extra)
    return result


def solver_report(**overrides: Any) -> dict[str, Any]:
    """Return a solver-metadata block with neutral defaults.

    Modes override only the fields they have; the no-solve paths keep the
    same key set without hand-writing a full block of zeros.
    """
    report: dict[str, Any] = {
        "backend": "none",
        "success": True,
        "status": 0,
        "cost": 0.0,
        "optimality": 0.0,
        "nfev": 0,
        "message": "",
        "residual_calls": 0,
        "residual_eval_time_s": 0.0,
        "residual_size": 0,
        "solver_dim": 0,
        "jac_sparsity_used": False,
        "jac_sparsity_shape": None,
        "residual_eval_mean_ms": 0.0,
        "relation_weight": 0.0,
        "relation_weight_schedule": [],
        "phase_schedule": [],
        "stage_history": [],
        "movement_weight": 0.0,
        "initial_guess_variables": 0,
    }
    report.update(overrides)
    return report


def reject_unknown_options(result: dict[str, Any], unknown: Mapping[str, Any]) -> bool:
    """Record unknown mode option names on ``result``; True if any were given."""
    if not unknown:
        return False
    result["errors"].append(f"Unknown {result['mode']} option(s): " + ", ".join(sorted(unknown)))
    result["termination"] = "invalid options"
    return True


def record_uninitialized_failure(system: Any, result: dict[str, Any]) -> bool:
    """Fill ``result`` and return True when an enforced relation needs an
    unsupplied, ungenerated free variable; the mode then returns ``result``."""
    required = system.required_uninitialized_free_variables()
    if not required:
        return False
    result["errors"].append(
        "Uninitialized required free variables: " + ", ".join(required)
        + ". These variables were not supplied and were not generated by active relations."
    )
    result["termination"] = "initialization failed"
    result["uninitialized_free_variables"] = list(system.uninitialized_free_variables)
    return True
